### ISSUE TITLE
why is `wcswidth('Hi\tthere) == -1`?

### ISSUE THREAD

**Issue by llimllib** [Z4JC/uwcwidth#1]
I ported your library over to node, including all the tests, and that one leaves me scratching my head a bit.

Is the reasoning that the tab character's width is not knowable?

**Comment by Z4JC** [comment]
`wcswidth` is a direct port of the POSIX.1-2016 [wcswidth](https://pubs.opengroup.org/onlinepubs/9699919799.2016edition/) call. Here's the paragraph in question:

> return -1 (if any of the first n wide-character codes in the wide-character string pointed to by pwcs is not a printable wide-character code).

Under ASCII, printable codes are in range `0x20` to `0x7e` (see [here](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/isprint-iswprint-isprint-l-iswprint-l?view=msvc-170), for example)

`\t` is ASCII `0x09`, thus not printable thus `-1` has to be returned.

My guess of the rationale for this behavior: to understand the exact spacing needed for `\t`, you have to know the terminal settings and the current cursor position.

For example, most of the terminals we all use are some variation of ANSI or VT100 terminals. Under these terminals, tab stops are programmable to arbitrary columns. For example: the first tab stop can be column 4, followed by column 10, followed by column 15. Without knowing where the tab stops are and where is the column where you begin to print the string,  you have no idea how wide the `\t` is going to be in terms of standard ASCII terminal characters. So, instead of guessing, the standard wants you to abort with `-1` and expects the caller of `wcswidth` to break up the string into pieces for which it hopes to know the exact terminal width and deal with everything else in some other way.

So glad you're porting `uwcwidth` to node :) I think it can be a fast and practical solution, with very small footprint.
Hoping some verison of `ugrapheme` is next on your list. The core of it, which detects the grapheme character breaks is only the first 300 lines or so of code in [ugrapheme.pyx](https://github.com/Z4JC/ugrapheme/blob/main/ugrapheme/ugrapheme.pyx) and maps into Javascript with minimal syntax changes.. Everything else is iterators and string operations that mimic what is available in python for regular strings.
